### ISSUE TITLE
Python build failing

### ISSUE THREAD

**Issue by joe-graham** [radare/radare2-bindings#191]
Build on Ubuntu 18.04 LTS failing with this error:

`r_core_wrap.cxx:7376:10:
error: 'r_core_read_at' was not declared in this scope
return r_core_read_at(self, addr, buf, size);`

It looks like [this commit](https://github.com/radare/radare2/commit/31ad955babbca1436deba2159414354f8f26ab41) removed that function.

**Comment by radare** [comment]
Edit the vapi and send a pr
