### ISSUE TITLE
RBin or RIO module error.

### ISSUE THREAD

**Issue by deft01** [radare/radare2-bindings#181]
I work with the official ubuntu docker 16.04.
I finally successfully compiled r2-bindings with r2pm. 

Im not using r2pipe cause when i wrote my program i saw on the r2 github that the bindings was recommanded. I had no idea (and its not written) the bindings were outdated/deprecated... Now for the futur I will use r2pipe but it would be great and a huge gain of time if i could use the bindings a last time.

When i execute with python2.7 the example scripts **test-r_bin.py** of r2-bindings/python i got this : 

```
root@103bf658b2ae:/# cat test-r_bin.py

try:
	from r_bin import *
except:
	from r2.r_bin import *

path="/bin/ls"

io = RIO()
desc = io.open(path, 0, 0)
if desc == None:
	print "Cannot open file"
	exit(1)

print "FD", desc.fd

b = RBin ()
b.iobind(io)

# XXX broken test because now RBin depends on RIO
b.load (path, 0, 0, 0, desc.fd, False)
baddr = b.get_baddr ()
print 'Base Address', baddr
print '-> Sections'
for i in b.get_sections ():
	print 'offset=0x%08x va=0x%08x size=%05i %s' % (
			i.paddr, baddr+i.vaddr, i.size, i.name)
root@103bf658b2ae:/#
root@103bf658b2ae:/#
root@103bf658b2ae:/#
root@103bf658b2ae:/# python test.py 
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    desc = io.open(path, 0, 0)
AttributeError: 'RIO' object has no attribute 'open'
```

**I have no errors with the unit tests on the io module :** 

```
root@103bf658b2ae:/radare2-regressions# cd unit/
root@103bf658b2ae:/radare2-regressions/unit# make
cc -I/root/../install/include/libr -g test_debruijn.c -o test_debruijn -L/root/../install/lib -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flag -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic -lr_crypto -lr_magic
cc -I/root/../install/include/libr -g test_base64.c -o test_base64 -L/root/../install/lib -lr_core -lr_config -lr_cons -lr_io -lr_util -lr_flag -lr_asm -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -
...
... (a lot of flags)

root@103bf658b2ae:/radare2-regressions/unit# ./test_io 
test_r_io_mapsplit OK
test_r_io_mapsplit2 OK
test_r_io_pcache OK
test_r_io_desc_exchange OK

```

There you can find the two classes : 
http://radare.org/vdoc/libr/Radare.RBin.Info.html
http://radare.org/vdoc/libr/Radare.RIO.html

**Comment by nartes** [comment]
Is it r2pm package, what's the link to it?
Why not to use r2pipe?

**Comment by Maijin** [comment]
It's in r2pm @nartes

**Comment by deft01** [comment]
Im not using r2pipe cause when i wrote my program i saw on the r2 github that the bindings was recommanded. I had no idea (and its not written) the bindings were outdated/deprecated... Now for the futur I will use r2pipe but it would be great and a huge gain of time if i could use the bindings a last time.

**Comment by nartes** [comment]
What's the name of the package?
```
siarhei_hp% R2PM_DBDIR=$PWD/tmp/r2pm PATH=$PWD/tmp/install/bin:$PATH LD_LIBRARY_PATH=$PWD/tmp/install/lib:$LD_LIBRARY_PATH tmp/install/bin/r2pm -s bindin
r2api-lua        [r2-api] Native Lua API bindings
r2api-perl       [r2-script] Native Perl API bindings
r2api-python             [r2-api] Native Python API bindings
r2b-lua          [syspkg] Native Lua SWIG bindings
```
There's r2-bindings package.

**Comment by radare** [comment]
R2pipe is the way to go since its inception. But i will update the bindings when i have some time. Its just too many work to maintain everything just by myself so i have to priorize and find better ways to reduce maintainability.

Feel free to send a pr fixing that its just editing the vapi files, the rest is autogenerated by valabind.

**Comment by nartes** [comment]
It would be good to specify the last working pair of radare2 and radare2-bindings, cause otherwise no way to stay at the working version.

**Comment by nartes** [comment]
Tried to rollback to September (no actual reason here), installed an older version of libvala (vala-git on archlinux, added #tag=0.36.0 to the repo link in PKGBUILD),
radare2-bindings: e05f318 (HEAD) Remove more deprecated apis
radare2: deb7c07c6 (HEAD) Intrusive augmented top-down red-black tree
Still get stupid errors.

https://github.com/radare/valabind/issues/43, valabind doesn't build because ccodegen is not used properly (either under 0.36.4, or wait till the upstream support will appear)
Currently, vala-git (0.40) has following libs:
```
vala-git /usr/lib/libvala-0.40.so                                                                                                                                                                                                
vala-git /usr/lib/libvala-0.40.so.0                                                                                                                                                                                              
vala-git /usr/lib/libvala-0.40.so.0.0.0                                                                                                                                                                                          
vala-git /usr/lib/libvaladoc-0.40.so                                                                                                                                                                                             
vala-git /usr/lib/libvaladoc-0.40.so.0                                                                                                                                                                                           
vala-git /usr/lib/libvaladoc-0.40.so.0.0.0                                                                                                                                                                                       
vala-git /usr/lib/vala-0.40/libvalaccodegen.so                                                                                                                                                                                   
vala-git /usr/lib/valadoc/doclets/devhelp/libdoclet.so                                                                                                                                                                           
vala-git /usr/lib/valadoc/doclets/gtkdoc/libdoclet.so                                                                                                                                                                            
vala-git /usr/lib/valadoc/doclets/html/libdoclet.so 
```
I am not an expert of vala, but can we use libvalaccodegen already?

**Comment by radare** [comment]
the working pair is the same version number, r2b will bump after r2 to match the version. the problem here is that valabind doesnt builds on latest vala, so until vala 0.40 is released we may probably stop supporting the native bindings. also native bindings introduce many possible issues that are not happening via r2pipe. so its better to use r2pipe and work on r2pipe-api to make language-friendly “api” bindings thru r2pipe.

**Comment by XVilka** [comment]
@radare Vala-0.40.4 was released, so what about this one?

**Comment by nartes** [comment]
Seems like the package valaccodegen has remained a private library. I didn't find anything related to exposing either CCodeBase class or the ccodegen package as a whole.

This issue https://bugzilla.gnome.org/show_bug.cgi?id=788837 has been just closed. I didn't think that it's really "STATUS: RESOLVED FIXED".

**Comment by radare** [comment]
?

**Comment by radare** [comment]
it should be fine now
